pybo/models.py
from pybo import db

class Question(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    subject=db.Column(db.String(200),nullable=False)
    content=db.Column(db.Text(),nullable=False)
    create_date=db.Column(db.DateTime(),nullable=False)

class Answer(db.Model):
    id=db.Column(db.Integer,primary_key=True)
    question_id=db.Column(db.Integer,db.ForeignKey('question.id',ondelete='CASCADE'))
    question=db.relationship('Question',backref=db.backref('answer_set',cascade='all,delete-orphan'))
    content=db.Column(db.Text(),nullable=False)
    create_date=db.Column(db.DateTime(),nullable=False)

pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField
from wtforms.validators import DataRequired

class QuestionForm(FlaskForm):
    subject=StringField('제목',validators=[DataRequired('제목은 필수 입력 항목입니다.')])
    content=TextAreaField('내용',validators=[DataRequired('내용은 필수 입력 항복입니다.')])

class AnswerForm(FlaskForm):
    content=TextAreaField('내용',validators=[DataRequired()])

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db=SQLAlchemy()
migrate=Migrate()

def create_app():
    app=Flask(__name__)
    app.config.from_object(config)

    #ORM
    db.init_app(app)
    migrate.init_app(app,db)

    from .import models

    #blueprint(route)
    from .views import main_views,question_views,answer_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(answer_views.bp)

    return app

pybo/views/answer_views.py
from datetime import datetime
from flask import Blueprint, redirect,url_for,request,render_template
from werkzeug.utils import redirect 
from ..forms import AnswerForm
from pybo import db

from pybo.models import Question,Answer 

bp=Blueprint('answer',__name__,url_prefix='/answer')

@bp.route('/create/<int:question_id>',methods=('POST',))
def create(question_id):
    form=AnswerForm()
    question=Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        content=request.form['content']
        answer=Answer(content=content,create_date=datetime.now())
        question.answer_set.append(answer)
        db.session.commit()
        return redirect(url_for('question.detail',question_id=question_id))
    return render_template(url_for('question/question.detail.html',question=question,form=form))

pybo/views/main_views.py
from flask import Blueprint, redirect,render_template, url_for
from pybo.models import Question

bp=Blueprint('main',__name__,url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'Hello,Pybo!'

@bp.route('/')
def index():
    return redirect(url_for('question._list'))

pybo/views/question_views.py
from flask import Blueprint,render_template,request,url_for
from pybo.models import Question
from pybo.forms import QuestionForm,AnswerForm

from datetime import datetime
from werkzeug.utils import redirect
from .. import db
from ..models import Question


bp=Blueprint('question',__name__,url_prefix='/question')

@bp.route('/list/')
def _list():
    question_list=Question.query.order_by(Question.create_date.desc())
    return render_template('question/question_list.html',question_list=question_list)
    
@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form=AnswerForm()
    question=Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html',question=question,question_id=question_id,form=form)

@bp.route('/create/',methods=['GET','POST'])
def create():
    form=QuestionForm()
    print('yyy')
    if request.method=='POST' and form.validate_on_submit():
        print('xxx')
        question=Question(subject=form.subject.data, content=form.content.data,create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        print('zzz')
    return render_template('question/question_form.html',form=form)
    

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <title>Hello,pybo!</title>
</head>
<body>
{% include "navbar.html"%}
    
{% block content %} 

{% endblock %}

<script src="{{url_for('static',filename='jquery-3.6.3.min.js')}}"></script>
<script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>    
</body>
</html>

pybo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a href="{{url_for('main.index')}}" class="navbar-brand">Pybo</a>
    <button 
        class="navbar-toggler ml-auto" 
        type="button" 
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="nav-link">계정생성</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">로그인</a>
            </li>
        </ul>
    </div>
</nav>

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">{{question.content}}</div>"
        </div>
    </div>
    <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">{{question.create_date}}</div>
    </div>


    <h5 class="border-bottom my-3 py-2">{{question.answer_set|length}}개의 답변이 있습니다.</h5>

    {% for answer in question.answer_set %} 
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space:pre-line;">{{answer.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">{{answer.create_date}}</div>
            </div>
        </div>
    </div>
    {%endfor%}


    <form action="{{url_for('answer.create',question_id=question_id)}}" method="post" class="my-3">
        {{form.csrf_token}}
        <div class="form-group">
            <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
    <button class="btn"><a href="{{url_for('question._list')}}">목록으로 돌아가기</a></button>
</div>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %} 
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>

    <form action="" class="post-form my-3" method="POST">
        {{form.csrf_token}}

        <!-- 오류확인코드 -->
        {% for field,errors in form.errors.items() %}
        <div class="alert alert-danger" role="'alert">
            <strong>{{form[field].label}}</strong>:{{','.join(erros)}}
        </div>
        {% endfor %} 

        {{form.subject.label}}
        {{form.subject(class="form-control")}}

        {{form.content.label}}
        {{form.content(class="form-control")}}
        
        <button class="btn btn-primary my-2"  type="submit">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thread-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list%} 
            {% for question in question_list%}
            <tr>
                <td>{{loop.index}}</td>
                <td>
                    <a href="{{url_for('question.detail',question_id=question.id)}}" class="href">{{question.subject}}</a>
                </td>
                <td>{{question.create_date}}</td>
            </tr>
            {% endfor %}
            {% else %} 
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{{url_for('question.create')}}" class="btn btn-primary">질문등록하기</a>
</div>
{% endblock%} 